name: Bug Report
description: 报告问题以帮助改进 Otter Music
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: 问题描述
      description: 请描述遇到的问题、复现步骤以及相关截图
      placeholder: |
        问题描述：

        复现步骤：
        1. 打开...
        2. 点击...
        3. 看到...

        截图：
    validations:
      required: true

  - type: input
    id: env
    attributes:
      label: 环境
      description: 平台/设备/系统版本/App版本/音源
      placeholder: Android / 红米K50 / Android 13 / v2.4.3 / Joox
